global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using Deciji_Letnji_Program.Entiteti;
global using NHibernate;
global using static DatabaseAccess.Extensions;
global using System.Diagnostics.CodeAnalysis;